<?php
use Pentagonal\TBot\Module\Core\Main\View;

if (!isset($this) || ! $this instanceof View) {
    return;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?= htmlentities((string) $this->getAttribute('title', 'Welcome'));?></title>
</head>
<body>

</body>
</html>